const DECREMENT_COUNTER = "DECREMENT_COUNTER";
const INCREMENT_COUNTER = "INCREMENT_COUNTER";
const DECREMENT_STEAL = "DECREMENT_STEAL";
const INCREMENT_STEAL = "INCREMENT_STEAL";
const RESET_PLAYER_COUNTER = "RESET_PLAYER_COUNTER";
const STEAL_FRAGMENTS = "STEAL_FRAGMENTS";
const RESET_PLAYER_STEAL_COUNTER = "RESET_PLAYER_STEAL_COUNTER";

export {
  DECREMENT_COUNTER,
  INCREMENT_COUNTER,
  RESET_PLAYER_COUNTER,
  STEAL_FRAGMENTS,
  DECREMENT_STEAL,
  INCREMENT_STEAL,
  RESET_PLAYER_STEAL_COUNTER
};
