const DECREMENT_COUNTER = "DECREMENT_COUNTER";
const INCREMENT_COUNTER = "INCREMENT_COUNTER";
const RESET_COUNTER = "RESET_COUNTER";
const STEAL_FRAGMENTS = "STEAL_FRAGMENTS";
const CAPTURE_FRAGMENTS = "CAPTURE_FRAGMENTS";

export {
  DECREMENT_COUNTER,
  INCREMENT_COUNTER,
  RESET_COUNTER,
  STEAL_FRAGMENTS,
  CAPTURE_FRAGMENTS,
};
