const DECREMENT_COUNTER = "DECREMENT_COUNTER";
const INCREMENT_COUNTER = "INCREMENT_COUNTER";
const RESET_PLAYER_COUNTER = "RESET_PLAYER_COUNTER";

export { DECREMENT_COUNTER, INCREMENT_COUNTER, RESET_PLAYER_COUNTER };
